# Generated by Django 3.2.7 on 2021-09-21 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreBodega', models.CharField(max_length=250)),
                ('nombreDepartamente', models.CharField(max_length=250)),
                ('direccion', models.CharField(max_length=250)),
                ('numTelefono', models.CharField(max_length=250)),
                ('fechaRegistro', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpi', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=250)),
                ('apellido', models.CharField(max_length=250)),
                ('genero', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('fechaNacimiento', models.DateField(max_length=250)),
                ('ocupacion', models.CharField(max_length=250)),
                ('fechaContratacion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAsignacion', models.CharField(max_length=250)),
                ('fecha', models.DateTimeField()),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignaciones.bodega')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignaciones.empleado')),
            ],
        ),
    ]
